package spell

var prefixes []prefix = []prefix{
	{"anti", 0},
	{"auto", 0},
	{"bio", 0},
	{"counter", 0},
	{"dis", 0},
	{"electro", 0},
	{"femto", 0},
	{"geo", 0},
	{"giga", 0},
	{"hyper", 0},
	{"im", IN},
	{"immuno", 0},
	{"in", IN},
	{"inter", 0},
	{"intra", 0},
	{"ir", IN},
	{"iso", 0},
	{"kilo", 0},
	{"magneto", 0},
	{"mega", 0},
	{"meta", 0},
	{"micro", 0},
	{"mid", 0},
	{"milli", 0},
	{"mini", 0},
	{"mis", 0},
	{"mono", 0},
	{"multi", 0},
	{"nano", 0},
	{"neuro", 0},
	{"non", 0},
	{"out", 0},
	{"over", 0},
	{"para", 0},
	{"photo", 0},
	{"pico", 0},
	{"poly", 0},
	{"pre", 0},
	{"pseudo", 0},
	{"psycho", 0},
	{"quasi", 0},
	{"radio", 0},
	{"re", 0},
	{"semi", 0},
	{"stereo", 0},
	{"sub", 0},
	{"super", 0},
	{"tele", 0},
	{"thermo", 0},
	{"ultra", 0},
	{"under", 0}, /*must precede un*/
	{"un", IN},
}

// TODO: Sort prefix alphabetically with shorter words coming after
// Not sure why under before un yet inter is after in
